config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  get 'projects/create'
  get 'projects/dashboard'

  root 'projects#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name,  presence: true
    validates :description, presence: true
    validates :state, presence: true

    enum state: [:propuesta, :en_progreso, :terminado]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def dashboard
    if params[:state].present?
      @projects = Project.where("state = ?", params[:state])
    else
      @projects = Project.all
    end
  end

  def create
    @project = Project.create(name: params[:name], description: params[:description], 
      start_date: params[:start_date], end_date: params[:end_date], state: params[:state].to_i)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioProyecto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <nav class="nav nav-pills nav-fill">
      <li class="nav-item h4">
          <%= link_to "Crear proyecto", projects_index_path %>
      </li>
      <li class="nav-item h4">
          <%= link_to "ver proyectos", projects_dashboard_path %>
      </li>
    </nav>

    <%= yield %>
</body>
</html>

app/views/projects/create.html.erb
<div class="container text-center mt-5">
    <% if @project.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> No se ha podido crear el proyecto:</h2>
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% else %>
        <h2>Proyecto creado con exito</h2>
    <% end %>
</div>

    

app/views/projects/dashboard.html.erb
<div class="container">
    <h2 class="text-center mt-5">Filtrar proyectos por estado</h2>
    <form class="form-inline my-2 my-lg-0 justify-content-center">
        <select class="custom-select" name="state" id="state">
            <option value="1">propuesta</option>
            <option value="0">en progreso</option>
            <option value="2">terminado</option>
        </select>
    <button type="submit" class="btn btn-dark btn-sm ml-3">Filtrar</button>
    </form>     
</div>   

<br>
   
<div class="container">
    <h1>Proyectos</h1>
    
    <table class="table mt-5">
  <thead>
    <tr class="h5">
      <th scope="col">id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Fecha inicio</th>
      <th scope="col">Fecha término</th>
      <th scope="col">Estado</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |pjt| %>
    <tr>
      <th scope="row"><%= pjt.id %></th>
      <td><%= pjt.name %></td>
      <td><%= pjt.description %></td>
      <td><%= pjt.start_date %></td>
      <td><%= pjt.end_date %></td>
      <td><%= pjt.state %></td>
    </tr>
    <% end %>
    </table>
</div>

app/views/projects/index.html.erb
<div class="container mt-5">
   <h2>Gestor de proyecto</h2>
   <p>Ingrese los datos</p>
   <form action="/projects/create" id="create_projects"method="get">
      <div class="form-group">
         <label for="exampleFormControlInput1">Nombre</label>
         <input type="text" class="form-control" name="name" placeholder="Nombre del proyecto">
      </div>
      <div class="form-group">
         <label for="exampleFormControlTextarea1">Descripcion</label>
         <textarea class="form-control" name="description" rows="3"></textarea>
      </div>
      <div class="form-group">
         <label for="exampleFormControlInput1">Fecha de inicio</label>
         <input type="date" class="form-control"  name="start_date" placeholder="Fecha Inicio">
      </div>
      <div class="form-group">
         <label for="exampleFormControlInput1">Fecha de termino</label>
         <input type="date" class="form-control"  name="end_date" placeholder="Fecha termino">
      </div>
      <div class="form-group">
         <label for="exampleFormControlSelect1">Estado del proyecto</label>
         <%= select_tag :state, options_for_select(Project.states) %>
      </div>
      <div class="form-group">
         <button type="submit" class="btn btn-secondary">Crear proyecto</button>
      </div>
   </form>
</div>